name: Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      project-version:
        required: true
        type: string

jobs:
  build:
    name: 'Build ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup perl (non Windows)
        uses: shogo82148/actions-setup-perl@v1

      - name: Install modules
        run: |
          cpanm PAR
          cpanm PAR::Packer

      - name: Build
        shell: bash
        run: |
          pp -o helloworld helloworld.pl

      - name: Assemble
        uses: jreleaser/release-action@v2
        with:
          arguments: assemble
        env:
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-assemble-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: artifact-${{ runner.os }}-${{ runner.arch }}
          path: |
            out/jreleaser/assemble/helloworld/archive/*.zip
